// <auto-generated />
using System;
using GestionRepuestosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionRepuestosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130033249_PrimeraMigracion")]
    partial class PrimeraMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionRepuestosAPI.Models.RepuestosStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadEnStock")
                        .HasColumnType("int");

                    b.Property<string>("CodigoOriginal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostoUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RepuestosStock");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Models.RepuestosVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioVentaUnitarioEnARS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RepuestoStockId")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RepuestoStockId");

                    b.ToTable("RepuestosVenta");
                });

            modelBuilder.Entity("GestionRepuestosAPI.Models.RepuestosVenta", b =>
                {
                    b.HasOne("GestionRepuestosAPI.Models.RepuestosStock", "RepuestoStock")
                        .WithMany()
                        .HasForeignKey("RepuestoStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepuestoStock");
                });
#pragma warning restore 612, 618
        }
    }
}
